###PostStudent
POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "Beltrano",
    "email": "beltrano@email.com",
    "birth_date": "1971-01-01"
}

###PostTeacher
POST http://localhost:3003/teacher
Content-Type: application/json

{
    "name": "Darvas",
    "email": "darvas@email.com",
    "birth_date": "1974-03-02"
}

###PostMission
POST http://localhost:3003/mission
Content-Type: application/json

{
    "name": "Edson",
    "start_date": "2020-05-01",
    "end_date": "2020-11-21",
    "module": "4"
}

###UpdateStudent
PUT http://localhost:3003/student
Content-Type: application/json

{
    "id": "5",
    "mission_id": "5"
}

###UpdateTeacher
PUT http://localhost:3003/teacher
Content-Type: application/json

{
    "id": "161123945",
    "mission_id": "161117099"
}

###GetStudentByAge
GET http://localhost:3003/student/161343w21


###GetStudentByMission
GET http://localhost:3003/student/mission/143


###GetTeacherByMission
GET http://localhost:3003/teacher/mission/161117099

###DeleteStudent
DELETE http://localhost:3003/student/10


###RemoveStudentFromMission
PUT http://localhost:3003/student/161108468

###RemoveTeacherFromMission
PUT http://localhost:3003/teacher/asdas


###GetStudentByHobby
GET http://localhost:3003/student/hobby/1