###PostStudent
POST http://localhost:3003/student
Content-Type: application/json

{
    "name": "Beltrano",
    "email": "beltrano@email.com",
    "birth_date": "1971-01-01"
}

###PostTeacher
POST http://localhost:3003/teacher
Content-Type: application/json

{
    "name": "Ciclano2",
    "email": "ciclano2@email.com",
    "birth_date": "1971-01-01"
}

###PostMission
POST http://localhost:3003/mission
Content-Type: application/json

{
    "name": "Jackson",
    "start_date": "2021-01-01",
    "end_date": "2021-07-01",
    "module": "1"
}

###UpdateStudent
PUT http://localhost:3003/student
Content-Type: application/json

{
    "id": "161108468",
    "mission_id": "5"
}